### ISSUE TITLE
Missing Linear Weights for Vicuna-13B-v1.1

### ISSUE THREAD

**Issue by eshoyuan** [OptimalScale/DetGPT#2]
The README mentions linear weights based on Vicuna-13B-v1.1, but I couldn't find them in the repo. Can you provide some guidance on where to find these weights or when they will be available if they're not yet released?

**Comment by pipilurj** [comment]
Hi there, you could download the files by executing the bash file download.sh
 in output_models. Thanks.

**Comment by eshoyuan** [comment]
I didn't realize that earlier. The name of the file is task_tuned.pth. Nonetheless, I managed to run the code without any issues. Thank you for your assistance!
You can substitute "ckpt: 'path/to/pretrained_linear_weights'" in the config with "ckpt: './output_models/task_tuned.pth'".
