### ISSUE TITLE
Nothing detected on the demo image, Help...

### ISSUE THREAD

**Issue by jru001** [OptimalScale/DetGPT#5]
Firstly, thanks LMFlow team for your amazing work in LLM and Multi-Modal !!!  
 
When I run the following script:
`CUDA_VISIBLE_DEVICES=0,1 python demo_detgpt.py --cfg-path configs/detgpt_tasktune_13b_coco.yaml`
All the models are loaded successfully:
![111](https://github.com/OptimalScale/DetGPT/assets/42190952/7add59f3-0dd1-403c-959f-9286d2f16c19)

But when I select the first demo,  and run the model, the output is "<object_names>":
![error](https://github.com/OptimalScale/DetGPT/assets/42190952/f23104b1-6736-4c0b-bbbf-45d3037748da)

I doubt the following layer( in DetGPT/detgpt/models/detgpt.py) is only initilize, but not loaded pretrained weights:
![222](https://github.com/OptimalScale/DetGPT/assets/42190952/27333753-ade6-4877-abb1-cb683b2d267d)

**Comment by serser** [comment]
Similar here, I tried every image like this,

![image](https://github.com/OptimalScale/DetGPT/assets/3620404/0238ed5c-5892-4e18-b12a-57566ce7b869)

It keeps on saying,

```
Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado Archivado
```

Any clue on this?

**Comment by serser** [comment]
> Similar here, I tried every image, but it keeps on saying the following as response,
> 
> ```
> Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado� Archivado�
> ```
> 
> The models seem to be loaded correctly.
> 
> ```
>  /home/me/conda_env/detgpt/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> Some weights of the model checkpoint at  /home/me/huggineface/hub/models--bert-base-uncased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias']
> - This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> Initializing Chat
> final text_encoder_type:  /home/me/huggineface/hub/models--bert-base-uncased
> Model loaded from /home/me/huggineface/hub/ShilongLiu/GroundingDINO/groundingdino_swinb_cogcoor.pth 
>  => _IncompatibleKeys(missing_keys=[], unexpected_keys=['label_enc.weight'])
> ********************
> 
> loaded detector
> 
> Loading VIT
> Loading VIT Done
> Loading Q-Former
> Loading Q-Former Done
> Loading LLAMA
> 
> Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]
> Loading checkpoint shards:  33%|███▎      | 1/3 [00:08<00:16,  8.25s/it]
> Loading checkpoint shards:  67%|██████▋   | 2/3 [00:15<00:07,  7.60s/it]
> Loading checkpoint shards: 100%|██████████| 3/3 [00:19<00:00,  6.21s/it]
> Loading checkpoint shards: 100%|██████████| 3/3 [00:19<00:00,  6.65s/it]
> /home/me/conda_env/detgpt/lib/python3.9/site-packages/gradio/outputs.py:43: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
>   warnings.warn(
> /home/me/conda_env/detgpt/lib/python3.9/site-packages/gradio/components.py:164: UserWarning: Unknown style parameter: full_width
>   warnings.warn(f"Unknown style parameter: {key}")
> /home/me/conda_env/detgpt/lib/python3.9/site-packages/gradio/components.py:164: UserWarning: Unknown style parameter: full_height
>   warnings.warn(f"Unknown style parameter: {key}")
> ```
> 
> And when it is processing,
> 
> ```
> A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
> /home/me/conda_env/detgpt/lib/python3.9/site-packages/transformers/modeling_utils.py:862: FutureWarning: The `device` argument is deprecated and will be removed in v5 of Transformers.
>   warnings.warn(
> /home/me/conda_env/detgpt/lib/python3.9/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
>   warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
> ```
> 
> Even if I've set `padding_side` in `detgpt/models/detgpt.py`.
> 
> ```
>         self.llama_tokenizer = LlamaTokenizer.from_pretrained(llama_model, use_fast=False)
>         self.llama_tokenizer.pad_token = self.llama_tokenizer.eos_token
>         self.llama_tokenizer.padding_side = 'left'
> ```
> 
> I am with the default packages as requirements.txt.
> 
> Any clue on this?

My fault, after [applying Vicuna delta on top of llama](https://github.com/lm-sys/FastChat/tree/main#vicuna-13b), it finally works!

**Comment by shizhediao** [comment]
Hi,
It is nice to hear that your issue has been solved.
Feel free to open a new issue if you encounter any problems.

Thank you!
